/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#0d1c2f",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "inverse-on-surface": "#eff1f3",
        "primary-fixed": "#dae2fd",
        "inverse-primary": "#bec6e0",
        "on-primary-fixed-variant": "#3f465c",
        "on-tertiary-fixed-variant": "#3a485c",
        "primary-container": "#131b2e",
        "inverse-surface": "#2d3133",
        "error": "#ba1a1a",
        "background": "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "on-primary-fixed": "#131b2e",
        "on-tertiary-container": "#76859b",
        "on-background": "#191c1e",
        "on-error-container": "#93000a",
        "on-surface-variant": "#45464d",
        "outline-variant": "#c6c6cd",
        "tertiary-fixed": "#d5e3fd",
        "on-secondary": "#ffffff",
        "surface-tint": "#565e74",
        "surface": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#b9c7e0",
        "tertiary": "#000000",
        "surface-container-high": "#e6e8ea",
        "on-secondary-container": "#54647a",
        "on-surface": "#191c1e",
        "secondary-fixed-dim": "#b7c8e1",
        "on-secondary-fixed": "#0b1c30",
        "surface-container": "#eceef0",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#38485d",
        "primary": "#000000",
        "on-error": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "secondary-fixed": "#d3e4fe",
        "secondary-container": "#d0e1fb",
        "surface-variant": "#e0e3e5",
        "outline": "#76777d",
        "secondary": "#505f76",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed": "#0d1c2f",
        "on-primary-container": "#7c839b",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "density": "compact",
        "unit": "4px",
        "margin": "24px",
        "container-max": "1440px",
        "gutter": "16px",
      },
      fontFamily: {
        "code-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
